// <auto-generated />
namespace SHOP_BanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateBrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBrand));
        
        string IMigrationMetadata.Id
        {
            get { return "202110131106266_updateBrand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
